/// Flutter icons NavigationBarIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationBarIcon
///      fonts:
///       - asset: fonts/NavigationBarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationBarIcon {
  NavigationBarIcon._();

  static const _kFontFam = 'NavigationBarIcon';
  static const String? _kFontPkg = null;

  static const IconData matching = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData learning = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
